Make a sequel to method chain
kstm-su/ztp pull request #35
Opened 2017-10-16 09:36 UTC by ugwis

## WHY
An error occurred at `docker-compose up -d`.
```
manager_1  | Unhandled rejection SequelizeDatabaseError: relation "images" does not exist
manager_1  |     at Query.formatError (/node_modules/sequelize/lib/dialects/postgres/query.js:351:16)
manager_1  |     at query.catch.err (/node_modules/sequelize/lib/dialects/postgres/query.js:86:18)
manager_1  |     at tryCatcher (/node_modules/bluebird/js/release/util.js:16:23)
manager_1  |     at Promise._settlePromiseFromHandler (/node_modules/bluebird/js/release/promise.js:512:31)
manager_1  |     at Promise._settlePromise (/node_modules/bluebird/js/release/promise.js:569:18)
manager_1  |     at Promise._settlePromise0 (/node_modules/bluebird/js/release/promise.js:614:10)
manager_1  |     at Promise._settlePromises (/node_modules/bluebird/js/release/promise.js:689:18)
manager_1  |     at Async._drainQueue (/node_modules/bluebird/js/release/async.js:133:16)
manager_1  |     at Async._drainQueues (/node_modules/bluebird/js/release/async.js:143:10)
manager_1  |     at Immediate.Async.drainQueues (/node_modules/bluebird/js/release/async.js:17:14)
manager_1  |     at runCallback (timers.js:781:20)
manager_1  |     at tryOnImmediate (timers.js:743:5)
manager_1  |     at processImmediate [as _immediateCallback] (timers.js:714:5)
```
Because the sequence of method-chain was not guaranteed.
```
sequelize.authenticate().then(() => {
  console.log('success to connect db');
  require('./models').migration();
  return standByRequest;
}).then(createStandby).catch(err => {
  console.error('unable to connect db:', err);
  process.exit();
});
```

## WHAT
Use promise.

2017-10-16 14:28 UTC, bgpat requested changes

2017-10-16 14:28 UTC, bgpat commented on manager/models/index.js
> +    Promise.all([pImages, pNodes]).then(succ).catch(err);
`pNodes` => `Images.sync()`

2017-10-16 14:28 UTC, bgpat commented on manager/models/index.js
> +  migration(succ, err) {
callback じゃなくて Promise 返したい

2017-10-17 01:28 UTC, bgpat commented on manager/models/index.js
> +  migration: () => {
`migration() {` では動かないですか？

2017-10-17 01:28 UTC, bgpat commented on manager/db.js
> +}).then(() => require('./models').migration()).then(() => standByRequest).then(createStandby).catch(err => {
長い

2017-10-17 01:29 UTC, bgpat requested changes

2017-10-17 01:29 UTC, bgpat commented on manager/models/index.js
> +  }
`,`

2017-10-17 06:02 UTC, ugwis commented on manager/models/index.js
> +  migration: () => {
大丈夫でした　https://github.com/kstm-su/ztp/pull/35/commits/68327cd18343eed60908d3667213a16e4bdfde4f

2017-10-17 06:02 UTC, ugwis commented on manager/db.js
> +}).then(() => require('./models').migration()).then(() => standByRequest).then(createStandby).catch(err => {
fix https://github.com/kstm-su/ztp/pull/35/commits/0c75eed8b44c7e0cb79dd5c134295915f23aacef

2017-10-17 06:04 UTC, ugwis commented on manager/models/index.js
> +  }
,とそれ以外のところもちょっと直しました　https://github.com/kstm-su/ztp/pull/35/commits/59ae7a7d1666ef5e688a067b2af82acf38df0c7a

2017-10-17 07:06 UTC, bgpat requested changes

2017-10-17 07:06 UTC, bgpat commented on manager/models/index.js
> +  }
なおってないのでは？

2017-10-17 07:07 UTC, bgpat approved these changes
LGTM

2017-10-17 07:22 UTC, merged